SENSOR_WINDOW_WIDTH = 1600
SENSOR_WINDOW_HEIGHT = 900
SENSOR_WINDOW_TITLE = 'Sensor Input'

SENSOR_X_COLOR = (100, 200, 200)
SENSOR_Y_COLOR = (200, 100, 200)
SENSOR_Z_COLOR = (200, 200, 100)
MAX_CURVE_HISTORY = 25000

DATA_NORMALIZATION_COEFFICIENT = 10000

REL_DIST_COLOR = (255, 255, 255)

SENSOR_READ_TIMER_TIMEOUT = 5

# SENSOR_WAIT_FOR_READY_STRING = 'Send any character to begin measuring'
SENSOR_WAIT_FOR_READY_STRING = 'Send any character to begin DMP programming and demo'

SENSOR_DATA_PREFIXES = ('aworld', 'ypr', 'areal')

MIN_SQUARE_INTERPRETER_NAME = 'Min square interpreter'

# i installed scripy, pyserial and vispy on global pip :(
INTERPRETER_WINDOW_WIDTH = 800
INTERPRETER_WINDOW_HEIGHT = 450


# SERIAL_PORT_BAUD_RATE = 38400
SERIAL_PORT_BAUD_RATE = 115200
SERIAL_PORT_NAME = '/dev/cu.usbserial-14610'

DEFAULT_MIN_SQUARE_GESTURE_LENGTH = 100
DEFAULT_MIN_SQUARE_THRESHOLD = 10000


