SENSOR_WINDOW_WIDTH = 1600
SENSOR_WINDOW_HEIGHT = 900
SENSOR_WINDOW_TITLE = 'Sensor Input'

SENSOR_X_COLOR = (0, 255, 255)
SENSOR_Y_COLOR = (255, 0, 255)
SENSOR_Z_COLOR = (255, 255, 0)
MAX_CURVE_HISTORY = 25000

REL_DIST_COLOR = (255, 255, 255)

SENSOR_READ_TIMER_TIMEOUT = 5

# SENSOR_WAIT_FOR_READY_STRING = 'Send any character to begin measuring'
SENSOR_WAIT_FOR_READY_STRING = 'Send any character to begin DMP programming and demo'

SENSOR_DATA_PREFIXES = ('aworld', 'ypr')

MIN_SQUARE_INTERPRETER_NAME = 'Min square interpreter'


INTERPRETER_WINDOW_WIDTH = 800
INTERPRETER_WINDOW_HEIGHT = 450


# SERIAL_PORT_BAUD_RATE = 38400
SERIAL_PORT_BAUD_RATE = 57600

DEFAULT_MIN_SQUARE_GESTURE_LENGTH = 100
DEFAULT_MIN_SQUARE_THRESHOLD = 10000


